# Lab 4a: Dynamic Programming

Lab associated with Module 4a: Dynamic Programming

***

In [1]:
# The following lines are used to increase the width of cells to utilize more space on the screen 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

/var/folders/0n/s19df3pj3515r5_vrmr7rst80000gn/T/ipykernel_66670/1945220536.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


***

### Section 0: Imports

In [2]:
import numpy as np

In [3]:
import math

In [4]:
from IPython.display import Image
from graphviz import Digraph
import time

Details of Digraph package: https://h1ros.github.io/posts/introduction-to-graphviz-in-jupyter-notebook/

***

### <font color='red'> Section 1: Write the code for finding the Longest Common Sub-sequence. Make sure you output the Matrix C and the longest sub-sequence. Test your code with various use-cases. </font>

In [5]:
### TODO ###
### Good Luck ###

def lcs_v1(x, y):
    # Oversize the matrix by 1 and populate with zeros.
    z = np.zeros(shape = (len(x)+1, len(y)+1))
    result = []
    
    for i in range(0, len(x)): # Check each row element
        for j in range(0, len(y)): # Against each column element.
            if x[i] == y[j]: # If we have a match, increments [i][j] by 1.
                z[i+1][j+1] = z[i][j]+1
            else:
                # Insert the max value of (above and left). 
                z[i+1][j+1] = max(z[i+1][j], z[i][j+1])
                
    # Loping backwards through the matrix to construct the LCS.  
    i = len(x)
    j = len(y)
            
    while i > 0:
        # Move to the cell (L or R) that has an equal value
        if z[i-1][j] == z[i][j]: # Checking left value
            i = i-1
        elif z[i][j-1] == z[i][j]: # Checking right value
            j = j-1
        # if both left and right are less than current. 
        elif z[i-1][j] < z[i][j] and z[i][j-1] < z[i][j]:
            result.append(x[i-1])
            i = i-1
            j = j-1
     
    result = result[::-1] # Reverse order of the array.
            
    return result, z


In [6]:
# test Case 11.3 from the lecture 11 notes. 
a = ['a','b','a','z','d','c']
b = ['b','a','c','b','a','d']

t0 = time.time()
result = lcs_v1(a, b)
t1 = time.time()
print('Time:', (t1-t0)*1000)
print('LCS:\n', result[0])
print('Matrix:\n', result[1], '\n')

Time: 0.11491775512695312
LCS:
 ['a', 'b', 'a', 'd']
Matrix:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 2. 2. 2.]
 [0. 1. 2. 2. 2. 3. 3.]
 [0. 1. 2. 2. 2. 3. 3.]
 [0. 1. 2. 2. 2. 3. 4.]
 [0. 1. 2. 3. 3. 3. 4.]] 



In [7]:
# test Case 1. 
x = ['a','c','c','g','g','q','f','a']
y = ['a','c','t','c','g','f','e','g','j','a','a']

t0 = time.time()
result = lcs_v1(x, y)
t1 = time.time()
print('Time:', (t1-t0)*1000)
print('LCS:\n', result[0])
print('Matrix:\n', result[1], '\n')


Time: 0.16999244689941406
LCS:
 ['a', 'c', 'c', 'g', 'g', 'a']
Matrix:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 4. 4. 4. 4. 4. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4. 4. 5. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 4. 4. 5. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 5. 5. 5. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 5. 5. 5. 5. 6. 6.]] 



In [8]:
# test Case 2. 
s1 = 'ldskfhjqwdhcqjnwdcljkqnwelfjqlsdncasnbdvabsdkjfhclhasdflojqsdpopdwenrmnwclkjbsofeihqpowierclqkjwneflkqcljkqlkwjbefkqjwherlkfqbwerkjhf'
s2 = 'laKSDHJNaeiufnaWLEFJqekhgakdjrghadrkgjhavcwjrhgalksjghrwalkjhasdffuyrenrnnrhsjsjcihlkhfbqelrnvblqkjsdhvaisdvihqlwejrblfjalksjghrwalkjhasdffuyrenrnnrhsjsjcihlkhfbqelrnvblqkjsdhvaisdvihqlwejrblfjalksjghrwalkjhasdffuyrenrnnrhsjsjcihlkhfbqelrnvblqkjsdhvaisdvihqlwejrblfj'

x = [char for char in s1]
y = [char for char in s2]

t0 = time.time()
result = lcs_v1(x, y)
t1 = time.time()
print('Time:', (t1-t0)*1000, 'n =', len(s1), 'm =', len(s2))
print('LCS:\n', result[0])
print('Matrix:\n', result[1], '\n')


Time: 34.07001495361328 n = 133 m = 266
LCS:
 ['l', 'k', 'h', 'j', 'd', 'h', 'c', 'j', 'w', 'd', 'c', 'l', 'k', 'q', 'e', 'l', 'j', 's', 'd', 'a', 's', 'd', 'v', 'a', 's', 'j', 'h', 'l', 'h', 'a', 's', 'd', 'f', 'e', 'n', 'r', 'n', 'c', 'l', 'k', 'b', 'q', 'e', 'r', 'l', 'q', 'k', 'j', 'w', 'e', 'f', 'l', 'k', 'j', 'l', 'k', 'j', 'e', 'j', 'h', 'l', 'k', 'f', 'q', 'e', 'r', 'k', 'j', 'h', 'f']
Matrix:
 [[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  1. ...  1.  1.  1.]
 [ 0.  1.  1. ...  2.  2.  2.]
 ...
 [ 0.  1.  2. ... 68. 68. 69.]
 [ 0.  1.  2. ... 69. 69. 69.]
 [ 0.  1.  2. ... 69. 70. 70.]] 



***

***

### Section 2: Unbounded Knapsack Problem

Let us build a solution to unbounded Knapsack problem.

In [9]:

def unboundedKnapsack(W, n, wt, vals, names):
    K = [0 for i in range(W + 1)] # Setting values of K to zero for each discrete weight.
    ITEMS = [[] for i in range(W + 1)] # Creating a set of lists to store items in for each corosponding weight. 
 
    for x in range(1, W + 1): # For each descrete weight from 1 to max Weight.
        K[x] = 0
        
        # For each item available to add to the knapsack. 
        for i in range(0, n): # Ajusted index to start from zero to capture the first item. 
            prev_k = K[x]
            
            if (wt[i] <= x): # Checking the weight of the current item against the current max weight of the knapsack.
                K[x] = max(K[x], K[x - wt[i]] + vals[i]) # Comparing the current value against the value of the current 
                                                         # item and adding the greater of the two to the knapsack
            if K[x] != prev_k: # If x was updated update the items. 
                ITEMS[x] = ITEMS[x - wt[i]] + names[i]
 
    return K[W], ITEMS[W]

In [10]:
#Test Case 1.

W = 6                   # Capacity (Max Weight)
wt = [1, 2, 3, 4]       # Weight 
vals = [ 1, 4, 6, 9]    # Value 
names = [["Turtle"], ["Globe"], ["WaterMelon"], ['Laptop']]

n = len(names)

print('We have {} items to chosse from.'.format(n))                

We have 4 items to chosse from.


In [11]:
K, ITEMS = unboundedKnapsack(W, n, wt, vals, names)

In [12]:
print('Total value of the knapsack:',K)
ITEMS

Total value of the knapsack: 13


['Laptop', 'Globe']

In [13]:
#Test Case 5.

W = 16  # Capacity (Max Weight)
wt =   [1, 2, 3, 4, 7, 8, 9, 10]       # Weight 
vals = [1, 3, 5, 6, 12, 12, 10, 13]    # Value 
names = [["Turtle"], ['HotDog'], ['Shoes'], ['Gold'], 
         ['Lemons'], ["Globe"], ["WaterMelon"], ['Laptop']]

n = len(names)

print('We have {} items to chosse from.'.format(n)) 

We have 8 items to chosse from.


In [14]:
K, ITEMS = unboundedKnapsack(W, n, wt, vals, names)

In [15]:
print('Total value of the knapsack:',K)
ITEMS

Total value of the knapsack: 27


['Lemons', 'Lemons', 'HotDog']

### Code Reflections
Further testing after adjusting the index of the inner loop tp start at 0 instead of 1, the algorithm successfully picks the item combination that maximises the value of items in the knapsack.

Walking through the algorithm.
* K: Declares an array with a length equal to the total weight W+1 to account for the 0 index and tracks the total value of the knapsack.
* ITEMS: Declares an array of arrays to hold the items of the knapsack at each iteration from weight = 1 through to the max weight. 
 * We then enter a for loop for each discrete weight from 1 to max weight W.
 * We immediately enter a second loop to loop through all the items available.
  * Entering the loop, we record the current value of K[x] as prev_k.
  * If: the weight of the current item is <= the current knapsack max weight (outer loop value), then update the value of K[x] if: 
    * the value of ( K[x - current weight]’s value + the value of the current item) is greater than the current value of K[x].
    * Then, if: The value of K[x] was updated, update the items to correspond with the comparison done above. 
 * At the completion of the loops, the algorithm returns the total value of the knapsack (K[W]) and the items now held in the knapsack. 







In [16]:
# Createing an item object to minimise the number of arrays. 

class Item:
    
    def __init__(self, name, wt, v):

        self.name = name
        self.weight = wt
        self.value = v
        
    def __str__(self):
        val = f'{self.name} (Weight:{self.weight} Value:{self.value})\n'
        return str(val) 

In [17]:
# Updated algorithm to use the objects.

def unb_knapsack(W, items):
    K = [0 for i in range(W + 1)] # Setting values of K to zero for each discrete weight.
    ITEMS = [[] for i in range(W + 1)] # Creating a set of lists to store items in for each corosponding weight.
    n = len(items)
 
    for x in range(1, W + 1): # For each descrete weight from 1 to max Weight.
        K[x] = 0
        
        # For each item available to add to the knapsack. 
        for i in range(0, n): # Ajusted index to start from zero to capture the first item. 
            prev_k = K[x]
            
            if (items[i].weight <= x): # Checking the weight of the current item against the current max weight of the knapsack.
                K[x] = max(K[x], K[x - items[i].weight] + items[i].value) # Comparing the current value against the value of the current 
                                                                          # item if it was added to the knapsack
            if K[x] != prev_k: # If K[x] was updated update the items. 
                if (len(ITEMS[x - items[i].weight]) == 0):
                    ITEMS[x] = [items[i]]
                else:
                    add = []
                    for j in range(0, len(ITEMS[x - items[i].weight])):
                        add.append(ITEMS[x - items[i].weight][j])
                    add.append(items[i])
                    ITEMS[x] = add
                        
                    
 
    return K[W], ITEMS[W]

In [18]:
#Test Case 3.

W = 6    # Capacity (Max Weight)
items = [Item('Turtle',1,1), Item('Globe',2,4), Item('WaterMelon',3,6), Item('Laptop',4,9)]

K, ITEMS = unb_knapsack(W, items)

print(f'Value of Knapsack:{K}\n')
print('Knapsack Contains:')
for i in range(0, len(ITEMS)):
    print(f' {ITEMS[i]}', end='')


Value of Knapsack:13

Knapsack Contains:
 Laptop (Weight:4 Value:9)
 Globe (Weight:2 Value:4)


In [19]:
#Test Case 4.

W = 19    # Capacity (Max Weight)
items = [Item('Turtle',1,1), Item('Globe',2,3), Item('WaterMelon',3,5), Item('Laptop',4,6),
        Item('Lemons',7,12), Item('HotDog',8,12), Item('Shoes',9,10), Item('Gold',10,13)]

K, ITEMS = unb_knapsack(W, items)

print(f'Value of Knapsack:{K}\n')
print('Knapsack Contains:')
for i in range(0, len(ITEMS)):
    print(f' {ITEMS[i]}', end='')


Value of Knapsack:32

Knapsack Contains:
 Lemons (Weight:7 Value:12)
 Lemons (Weight:7 Value:12)
 WaterMelon (Weight:3 Value:5)
 Globe (Weight:2 Value:3)


***

### <font color='red'> Section 3: In the earlier activity, you analysed the code for unbounded knapsack. Based on the algorithm discussed in this section, implement an solution to do 0/1 Knapsack. Make sure you test your algorithms for various test-cases. </font>

In [21]:
#### TODO ####
### Good Luck ###

def zero_one_knapsack(W, wt, v, names):
    n = len(v)
    # Creating a matrix of 0's
    K = np.zeros(shape = (W+1, n+1))
    
    # Looping through each max weight.
    for x in range(1, W+1): 
        # Looping through each item
        for j in range(1, n+1):
            K[x][j] = K[x][j-1]
             # Comparing the weight of the current item 
                # against current max weight.
            if (wt[j-1] <= x):
                # Maximising the current value byt chossing the max value.
                K[x][j] = max(K[x][j], K[x-wt[j-1]][j-1] + v[j-1]) 
                
    return K[W][n], K


In [22]:
#Test Case 1.

W = 3                   # Capacity (Max Weight)
wt = [1, 2, 3]          # Weight 
v = [ 1, 4, 6]          # Value 
names = [["Turtle"], ["Globe"], ["WaterMelon"]]

print('We have {} items to chosse from.'.format(n))   

We have 8 items to chosse from.


In [23]:
result = zero_one_knapsack(W, wt, v, names)
print(f'Optimal Value: {result[0]}')
print(f'Results Matrix:\n{result[1]}')

Optimal Value: 6.0
Results Matrix:
[[0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 4. 4.]
 [0. 1. 5. 6.]]


In [24]:
#Test Case 2.

W = 6                   # Capacity (Max Weight)
wt = [1, 2, 3, 4]       # Weight 
v = [ 1, 4, 6, 9]       # Value 
names = [["Turtle"], ["Globe"], ["WaterMelon"], ['Laptop']]

print('We have {} items to chosse from.'.format(n))   

We have 8 items to chosse from.


In [25]:
result = zero_one_knapsack(W, wt, v, names)
print(f'Optimal Value: {result[0]}')
print(f'Results Matrix:\n{result[1]}')

Optimal Value: 13.0
Results Matrix:
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.]
 [ 0.  1.  4.  4.  4.]
 [ 0.  1.  5.  6.  6.]
 [ 0.  1.  5.  7.  9.]
 [ 0.  1.  5. 10. 10.]
 [ 0.  1.  5. 11. 13.]]


In [26]:
#Test Case 3.

W = 16  # Capacity (Max Weight)
wt =   [1, 2, 3, 4, 7, 8, 9, 10]       # Weight 
v =    [1, 3, 5, 6, 12, 12, 10, 13]    # Value 
names = [["Turtle"], ['HotDog'], ['Shoes'], ['Gold'], 
         ['Lemons'], ["Globe"], ["WaterMelon"], ['Laptop']]


print('We have {} items to chosse from.'.format(n)) 

We have 8 items to chosse from.


In [27]:
result = zero_one_knapsack(W, wt, v, names)
print(f'Optimal Value: {result[0]}')
print(f'Results Matrix:\n{result[1]}')

Optimal Value: 26.0
Results Matrix:
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  3.  3.  3.  3.  3.  3.  3.]
 [ 0.  1.  4.  5.  5.  5.  5.  5.  5.]
 [ 0.  1.  4.  6.  6.  6.  6.  6.  6.]
 [ 0.  1.  4.  8.  8.  8.  8.  8.  8.]
 [ 0.  1.  4.  9.  9.  9.  9.  9.  9.]
 [ 0.  1.  4.  9. 11. 12. 12. 12. 12.]
 [ 0.  1.  4.  9. 12. 13. 13. 13. 13.]
 [ 0.  1.  4.  9. 14. 15. 15. 15. 15.]
 [ 0.  1.  4.  9. 15. 17. 17. 17. 17.]
 [ 0.  1.  4.  9. 15. 18. 18. 18. 18.]
 [ 0.  1.  4.  9. 15. 20. 20. 20. 20.]
 [ 0.  1.  4.  9. 15. 21. 21. 21. 21.]
 [ 0.  1.  4.  9. 15. 23. 23. 23. 23.]
 [ 0.  1.  4.  9. 15. 24. 24. 24. 24.]
 [ 0.  1.  4.  9. 15. 26. 26. 26. 26.]]


Class Room Test-case

In [28]:
# Test Case 4

W = 10
v = [20, 8, 14, 13, 35]
wt = [6, 2, 4, 3, 11]
names = [6, 2, 4, 3, 11]

n = len(v)

print('We have {} items'.format(n))   

We have 5 items


In [29]:
result = zero_one_knapsack(W, wt, v, names)
print(f'Optimal Value: {result[0]}')
print(f'Results Matrix:\n{result[1]}')

Optimal Value: 35.0
Results Matrix:
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  8.  8.  8.  8.]
 [ 0.  0.  8.  8. 13. 13.]
 [ 0.  0.  8. 14. 14. 14.]
 [ 0.  0.  8. 14. 21. 21.]
 [ 0. 20. 20. 22. 22. 22.]
 [ 0. 20. 20. 22. 27. 27.]
 [ 0. 20. 28. 28. 28. 28.]
 [ 0. 20. 28. 28. 35. 35.]
 [ 0. 20. 28. 34. 35. 35.]]


***

***