<a href="https://colab.research.google.com/github/m1ckw/SIT320_Weekly_Activities/blob/main/WK01_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
np.random.seed(1)  # seed for reproducibility

x = np.random.randint(10, size=10)  # One-dimensional array
x

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9])

In [15]:
size = len(x)
count = 0
while (count < size-1):
    print(x[count] * x[count+1])
    count = count+1

40
72
45
0
0
0
7
42
54


In [16]:
for i in x:
    if x[i] % 2 == 0:
        print(x[i], " is an EVEN number.")
    else:
        print(x[i], " is an ODD number.")

0  is an EVEN number.
6  is an EVEN number.
9  is an ODD number.
0  is an EVEN number.
5  is an ODD number.
5  is an ODD number.
8  is an EVEN number.
7  is an ODD number.
1  is an ODD number.
9  is an ODD number.


In [17]:
print(x)
x.sort()
print(x)

[5 8 9 5 0 0 1 7 6 9]
[0 0 1 5 5 6 7 8 9 9]
